#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Q-Learning for Maze Navigation
Python 2.7 | ROS Melodic

Training: pure logical simulation using the CSV grid (fast, no Gazebo needed)
Testing:  loads the saved Q-table and controls the TurtleBot2 in Gazebo via ROS

Usage:
    Train:  python q_learning_maze.py --train --maze ~/ros_mazes/csv/maze_01.csv
    Test:   python q_learning_maze.py --test  --maze ~/ros_mazes/csv/maze_01.csv
"""

import rospy
import math
import numpy as np
import random
import os
import csv
import json
import sys

from std_msgs.msg import String
from std_msgs.msg import Int32MultiArray
from geometry_msgs.msg import Twist
from nav_msgs.msg import Odometry
from tf.transformations import euler_from_quaternion

# MAZE LOADER
def load_grid(csv_path):
    grid = []
    with open(csv_path, 'r') as f:
        for row in csv.reader(f):
            cleaned = [c.strip() for c in row if c.strip() != '']
            if cleaned:
                grid.append([int(c) for c in cleaned])
    return np.array(grid, dtype=float)


def load_config(json_path):
    """Load start/goal cells, their Gazebo coordinates, and the map resolution
    from the JSON generated by csv_to_ros_map.py.
    Resolution is stored there to avoid hardcoding it here."""
    with open(json_path, 'r') as f:
        data = json.load(f)
    start_cell = tuple(data['start']['cell'])
    goal_cell = tuple(data['goal']['cell'])
    goal_gz = tuple(data['goal']['gazebo'])
    resolution = float(data.get('resolution', 0.5))
    offset_x = float(data.get('offset_x', 0.0))
    offset_y = float(data.get('offset_y', 0.0))
    return start_cell, goal_cell, goal_gz, resolution, offset_x, offset_y


# GRIDWORLD
class GridWorld(object):
    FREE = 0.0
    GOAL = 1.0
    TRAP = -1.0
    BONUS = 0.5
    WALL = 9.0

    def __init__(self, grid, start_cell, goal_cell):
        self.grid = grid.copy()
        self.n_rows = grid.shape[0]
        self.n_cols = grid.shape[1]
        self.start_state = start_cell
        self.goal_cell = goal_cell
        self.state = self.start_state
        self.grid[self.grid == 1.0] = self.WALL
        self.grid[goal_cell] = self.GOAL
	self.dynamic_obstacles = set()

    def reset(self):
        self.state = self.start_state
        return self.state

    def is_terminal(self, state):
        value = self.grid[state]
        return value == self.GOAL or value == self.TRAP

    def get_next_state(self, state, action):
        row, col = state

        if action == 0:    # UP
            row = max(0, row - 1)
        elif action == 1:  # RIGHT
            col = min(self.n_cols - 1, col + 1)
        elif action == 2:  # DOWN
            row = min(self.n_rows - 1, row + 1)
        elif action == 3:  # LEFT
            col = max(0, col - 1)

        candidate = (row, col)

        if self.grid[candidate] == self.WALL:
            return state

	if candidate in self.dynamic_obstacles:
            return state

        return candidate

    def step(self, action):
        next_state = self.get_next_state(self.state, action)

        if next_state == self.state:
            return self.state, -20, False

        reward = -5
        cell_value = self.grid[next_state]

        if cell_value == self.GOAL:
            reward += 100
        elif cell_value == self.TRAP:
            reward -= 45
        elif cell_value == self.BONUS:
            reward += 10
            self.grid[next_state] = self.FREE

        self.state = next_state
        done = self.is_terminal(next_state)
        return next_state, reward, done

    def get_candidate_state(self, state, action):

    	row, col = state

    	if action == 0:
            row = max(0, row - 1)

    	elif action == 1:
            col = min(self.n_cols - 1, col + 1)

    	elif action == 2:
            row = min(self.n_rows - 1, row + 1)

    	elif action == 3:
            col = max(0, col - 1)

    	return (row, col)

    def get_reward(self, state, action, next_state):

    	if next_state == state:
	    candidate = self.get_candidate_state(state, action)

            if candidate in self.dynamic_obstacles:
            	return -100

            return -20

    	reward = -5

    	if self.grid[next_state] == self.GOAL:
            reward += 100

    	return reward

    def print_grid(self):
        for i in range(self.n_rows):
            row = ""
            for j in range(self.n_cols):
                if (i, j) == self.start_state:
                    row += " S "
                elif (i, j) == self.goal_cell:
                    row += " G "
                elif self.grid[i, j] == self.TRAP:
                    row += " T "
                elif self.grid[i, j] == self.WALL:
                    row += " W "
                elif self.grid[i, j] == self.BONUS:
                    row += " B "
                else:
                    row += " . "
            print(row)
        print("")


# Q-LEARNING AGENT
class QLearningAgent(object):
    def __init__(self, n_rows, n_cols,
                 learning_rate=0.1,
                 discount_factor=0.95,
                 exploration_rate=1.0,
                 min_exploration_rate=0.01,
                 exploration_decay=0.995):
        self.n_rows = n_rows
        self.n_cols = n_cols
        self.learning_rate = learning_rate
        self.discount_factor = discount_factor
        self.exploration_rate = exploration_rate
        self.min_exploration_rate = min_exploration_rate
        self.exploration_decay = exploration_decay
        self.q_table = np.zeros((n_rows, n_cols, 4), dtype=float)

    def choose_action(self, state):
        if random.uniform(0, 1) < self.exploration_rate:
            return random.randint(0, 3)
        q_values = self.q_table[state]
        max_q = np.max(q_values)
        best_actions = np.where(q_values == max_q)[0]
        return int(random.choice(best_actions))

    def update_q_value(self, state, action, reward, next_state, done):
        current_q = self.q_table[state][action]
        if done:
            target = reward
        else:
            target = reward + self.discount_factor * np.max(self.q_table[next_state])
        self.q_table[state][action] += self.learning_rate * (target - current_q)

    def decay_exploration(self):
        self.exploration_rate = max(
            self.min_exploration_rate,
            self.exploration_rate * self.exploration_decay
        )

    def local_value_iteration(self, env, center, radius=6, iterations=50):

    	center_row, center_col = center

    	for _ in range(iterations):

            new_q = self.q_table.copy()

            for row in range(env.n_rows):

            	for col in range(env.n_cols):

                    if abs(row-center_row) > radius:
                    	continue

                    if abs(col-center_col) > radius:
                    	continue

                    state = (row,col)

                    if env.grid[state] == env.WALL:
                    	continue

                    for action in range(4):

                    	next_state = env.get_next_state(state, action)

                    	reward = env.get_reward(state, action, next_state)

			old_q = self.q_table[row,col,action]

			target = reward + (self.discount_factor * np.max(self.q_table[next_state]))

                    	new_q[row,col,action] = (0.2 * old_q + 0.8 * target)

            self.q_table = new_q

    def print_policy(self, env):
        arrows = ['^', '>', 'v', '<']
        print("\nPOLICY\n")
        for i in range(self.n_rows):
            row = ""
            for j in range(self.n_cols):
                if (i, j) == env.goal_cell:
                    row += " G "
                elif env.grid[i, j] == GridWorld.TRAP:
                    row += " T "
                elif env.grid[i, j] == GridWorld.WALL:
                    row += " W "
                else:
                    best = np.argmax(self.q_table[i, j])
                    row += " " + arrows[best] + " "
            print(row)
        print("")


# TRAINING (logical, no Gazebo)
def train_agent(env, agent, action_pub, state_pub, episodes=30000, max_steps=200):
    for episode in range(episodes):
        state = env.reset()
        done = False
        steps = 0
        visit_count = {}

        while not done and steps < max_steps and not rospy.is_shutdown():
            action = agent.choose_action(state)
            next_state, reward, done = env.step(action)

            if next_state not in visit_count:
                visit_count[next_state] = 0
            visit_count[next_state] += 1
            reward -= visit_count[next_state] * 0.5

            agent.update_q_value(state, action, reward, next_state, done)

            action_msg = String()
            action_msg.data = "episode={} state={} action={} reward={}".format(
                episode, state, action, reward)
            action_pub.publish(action_msg)

            state_msg = Int32MultiArray()
            state_msg.data = [next_state[0], next_state[1]]
            state_pub.publish(state_msg)

            state = next_state
            steps += 1

        agent.decay_exploration()

        if episode % 100 == 0:
            rospy.loginfo("Episode {} | epsilon={}".format(
               episode, round(agent.exploration_rate, 4)))

    rospy.loginfo("Training finished")

# GAZEBO TESTING
class GazeboTester(object):
    def __init__(self, agent, env, goal_gz, resolution, offset_x, offset_y):
        self.agent = agent
        self.env = env
        self.goal_gz = goal_gz
        self.resolution = resolution
        self.current_gz = (0.0, 0.0)
        self.current_yaw = 0.0
        self.offset_x = offset_x
        self.offset_y = offset_y
        self.virtual_obstacles = []
	self.replanned_obstacles = set()
	self.visit_counts = {}

        rospy.Subscriber('/odom', Odometry, self._odom_callback)
        rospy.sleep(1.0)

        self.spawn_x = self.current_gz[0]
        self.spawn_y = self.current_gz[1]

        self.vel_pub = rospy.Publisher('/cmd_vel_mux/input/navi', Twist, queue_size=10)

        self.MOVEMENTS = {
            0: (-1,  0),  # UP (North)
            1: ( 0,  1),  # RIGHT (East)
            2: ( 1,  0),  # DOWN (South)
            3: ( 0, -1)   # LEFT (West)
        }

        self.last_visited_cell = None
        self.last_action = None

    def _odom_callback(self, msg):
        x = msg.pose.pose.position.x
        y = msg.pose.pose.position.y
        self.current_gz = (x, y)

        q = msg.pose.pose.orientation
        _, _, yaw = euler_from_quaternion([q.x, q.y, q.z, q.w])
        self.current_yaw = yaw

    def gz_to_cell(self, x, y):
        row = int(round(self.env.n_rows - 1 - (y - self.spawn_y + self.offset_y - self.resolution / 2.0) / self.resolution))
        col = int(round((x - self.spawn_x + self.offset_x - self.resolution / 2.0) / self.resolution))
        row = max(0, min(self.env.n_rows - 1, row))
        col = max(0, min(self.env.n_cols - 1, col))
        return (row, col)

    def evaluate_evasion_strategy(self, current_state):

    	row, col = current_state

    	best_action = None
    	best_q = -float('inf')

    	for action in range(4):

            dr, dc = self.MOVEMENTS[action]

            next_row = row + dr
            next_col = col + dc

            if not (0 <= next_row < self.env.n_rows):
            	continue

            if not (0 <= next_col < self.env.n_cols):
            	continue

            next_cell = (next_row, next_col)

            if self.env.grid[next_cell] == self.env.WALL:
            	continue

            if next_cell in self.env.dynamic_obstacles:
            	continue

            q = self.agent.q_table[current_state][action]

            if q > best_q:
            	best_q = q
            	best_action = action

	if best_action is None:
            return 0

    	return best_action

    def detect_obstacle_ahead(self, current_state, intended_action):

    	dr, dc = self.MOVEMENTS[intended_action]

    	obstacle_cell = (current_state[0] + dr, current_state[1] + dc)

    	if obstacle_cell in self.env.dynamic_obstacles:
            return True, obstacle_cell

    	return False, None

    def trigger_replanning(self, obstacle_cell, current_cell):
    	rospy.logwarn("[REPLAN] Dynamic obstacle detected at {}".format(obstacle_cell))
    	self.env.dynamic_obstacles.add(obstacle_cell)

    	# Penalize all direct actions that conduct to the obstacle
    	obs_row, obs_col = obstacle_cell
    	movements = {0: (-1,0), 1: (0,1), 2: (1,0), 3: (0,-1)}
    	for r in range(self.env.n_rows):
            for c in range(self.env.n_cols):
            	for action, (dr, dc) in movements.items():
                    if (r + dr, c + dc) == obstacle_cell:
                    	self.agent.q_table[r, c, action] = -9999.0

    	# Propagate over robot, not obstacle
    	self.agent.local_value_iteration(env=self.env, center=current_cell, radius=12, iterations=200)
    	rospy.logwarn("[REPLAN] Value iteration completed")

    def move_to_cell(self, action, speed=0.2, angular_speed=1.0):
        target_yaws = {0: math.pi/2, 1: 0.0, 2: -math.pi/2, 3: math.pi}
        target_yaw = target_yaws[action]
        rate = rospy.Rate(10)

        # ROTATION CONTROL LOOP
        while not rospy.is_shutdown():
            error = target_yaw - self.current_yaw
            error = math.atan2(math.sin(error), math.cos(error))
            if abs(error) < 0.05:
                self.vel_pub.publish(Twist())
                break
            kp_angular = 1.5
            twist = Twist()
            raw_speed = kp_angular * error
            twist.angular.z = max(min(raw_speed, angular_speed), -angular_speed)
            self.vel_pub.publish(twist)
            rate.sleep()

        self.vel_pub.publish(Twist())
        rospy.sleep(0.2)

        # LINEAR VELOCITY PROGRESSION LOOP
        current_row, current_col = self.gz_to_cell(self.current_gz[0], self.current_gz[1])
        dr, dc = self.MOVEMENTS[action]
        target_row = current_row + dr
        target_col = current_col + dc

        target_x = (target_col * self.resolution) + self.spawn_x - self.offset_x + (self.resolution / 2.0)
        target_y = self.spawn_y - self.offset_y + (self.resolution / 2.0) + ((self.env.n_rows - 1 - target_row) * self.resolution)

        rospy.loginfo("[CONTROL] Target cell coordinate set to Row: {}, Col: {} -> GZ: x={}, y={}".format(
            target_row, target_col, round(target_x,3), round(target_y,3)))

        while not rospy.is_shutdown():
            error_x = target_x - self.current_gz[0]
            error_y = target_y - self.current_gz[1]
            distance_error = math.sqrt(error_x**2 + error_y**2)

            if distance_error < 0.04:
                break

            kp_linear = 1.2
            twist = Twist()
            raw_linear_speed = kp_linear * distance_error
            twist.linear.x = max(min(raw_linear_speed, speed), 0.02)

            yaw_error = target_yaw - self.current_yaw
            yaw_error = math.atan2(math.sin(yaw_error), math.cos(yaw_error))
            twist.angular.z = 0.8 * yaw_error

            self.vel_pub.publish(twist)
            rate.sleep()

        self.vel_pub.publish(Twist())
        rospy.sleep(0.3)
        rospy.loginfo("moved to gz=({},{})".format(round(self.current_gz[0],3), round(self.current_gz[1],3)))

    def run(self, max_steps=200):
        """
        [FIXED ALL BUGS] Main operational execution loop in Gazebo.
        Ensures strict wall-filtering, sliding-window freezes, and history flushes.
        """
        rospy.loginfo("Starting Gazebo test run with Sequential Alignment and Bulletproof Q-table Protection")
        rate = rospy.Rate(2)
        steps = 0

        rospy.loginfo("spawn=({},{}) offset=({},{})".format(self.spawn_x, self.spawn_y, self.offset_x, self.offset_y))

        while not rospy.is_shutdown() and steps < max_steps:
            current_state = self.gz_to_cell(self.current_gz[0], self.current_gz[1])

	    self.visit_counts[current_state] = self.visit_counts.get(current_state, 0) + 1
	    if self.visit_counts[current_state] > 3:
    		rospy.logwarn("[LOOP] Loop detected in {}, aggresive replan".format(current_state))
    		self.agent.local_value_iteration(env=self.env, center=current_state, radius=12, iterations=500)
    		self.visit_counts.clear()

            # --- BUG FIX: Global wall safety filter checked on every single regular iteration step ---
            intended_action = self.evaluate_evasion_strategy(current_state)

	    # DEMO ONLY
	    if (3,4) == current_state and (3,5) not in self.env.dynamic_obstacles:
    		rospy.logwarn("[DEMO] Injecting obstacle at (3,5)")
    		self.env.dynamic_obstacles.add((3,5))

	    if (4,4) == current_state and (4,5) not in self.env.dynamic_obstacles:
    		rospy.logwarn("[DEMO] Injecting obstacle at (4,5)")
    		self.env.dynamic_obstacles.add((4,5))

	    if (5,4) == current_state and (5,5) not in self.env.dynamic_obstacles:
    		rospy.logwarn("[DEMO] Injecting obstacle at (5,5)")
    		self.env.dynamic_obstacles.add((5,5))

	    if (7,8) == current_state and (8,8) not in self.env.dynamic_obstacles:
    		rospy.logwarn("[DEMO] Injecting obstacle at (8,8)")
    		self.env.dynamic_obstacles.add((8,8))

	    if (7,7) == current_state and (8,7) not in self.env.dynamic_obstacles:
    		rospy.logwarn("[DEMO] Injecting obstacle at (8,7)")
    		self.env.dynamic_obstacles.add((8,7))

	    if (6,8) == current_state and (7,8) not in self.env.dynamic_obstacles:
    		rospy.logwarn("[DEMO] Injecting obstacle at (7,8)")
    		self.env.dynamic_obstacles.add((7,8))

	    if (5,8) == current_state and (6,8) not in self.env.dynamic_obstacles:
    		rospy.logwarn("[DEMO] Injecting obstacle at (6,8)")
    		self.env.dynamic_obstacles.add((6,8))

	    if (4,8) == current_state and (5,8) not in self.env.dynamic_obstacles:
    		rospy.logwarn("[DEMO] Injecting obstacle at (5,8)")
    		self.env.dynamic_obstacles.add((5,8))

            # ROTATIONAL ORIENTATION ALIGNMENT before moving forward
            target_yaws = {0: math.pi/2, 1: 0.0, 2: -math.pi/2, 3: math.pi}
            target_yaw = target_yaws[intended_action]
            rot_rate = rospy.Rate(10)

            while not rospy.is_shutdown():
                error = target_yaw - self.current_yaw
                error = math.atan2(math.sin(error), math.cos(error))
                if abs(error) < 0.05:
                    self.vel_pub.publish(Twist())
                    break
                kp_angular = 1.5
                twist = Twist()
                raw_speed = kp_angular * error
                twist.angular.z = max(min(raw_speed, 1.0), -1.0)
                self.vel_pub.publish(twist)
                rot_rate.sleep()

            rospy.sleep(0.1)

            # POST-ROTATION ADVANCE CLEARANCE CHECKING
	    obstacle_detected, obstacle_cell = (self.detect_obstacle_ahead(current_state, intended_action))

	    if obstacle_detected:
    		self.trigger_replanning(obstacle_cell, current_state)
    		continue

            # INITIATE KINEMATIC DISPLACEMENT CONTROL
            self.last_visited_cell = current_state
            self.last_action = intended_action
            rospy.loginfo("Cell {} -> selected action {}".format(current_state, intended_action))
            self.move_to_cell(intended_action)

            # SLIDING WINDOW LOOP BACKUP DETECTION METHOD
            new_state = self.gz_to_cell(self.current_gz[0], self.current_gz[1])

            # TERMINAL DESTINATION EUCLIDEAN CHECKS
            x, y = self.current_gz
            dist = ((x - self.goal_gz[0])**2 + (y - self.goal_gz[1])**2) ** 0.5
            rospy.loginfo("pos=({},{}) goal_gz={} dist={}".format(round(x,3), round(y,3), self.goal_gz, round(dist,3)))

            if dist < self.resolution * 0.75:
                rospy.loginfo("Goal reached successfully via Runtime Learning adaptation!")
                break

            steps += 1
            rate.sleep()

# SAVE / LOAD
def save_q_table(agent, filename="q_table.npy"):
    np.save(filename, agent.q_table)
    rospy.loginfo("Q-table saved to {}".format(filename))


def load_q_table(agent, filename="q_table.npy"):
    if os.path.exists(filename):
        loaded = np.load(filename)
        if loaded.shape == agent.q_table.shape:
            agent.q_table = loaded
            rospy.loginfo("Q-table loaded from {}".format(filename))
        else:
            rospy.logwarn("Shape mismatch: expected {}, got {}".format(
                agent.q_table.shape, loaded.shape))
    else:
        rospy.logwarn("Q-table file not found: {}".format(filename))


# MAIN
def main():
    mode = '--train'
    maze_path = os.path.expanduser('~/ros_mazes/csv/maze_01.csv')

    for i, arg in enumerate(sys.argv[1:]):
        if arg in ('--train', '--test'):
            mode = arg
        elif arg == '--maze' and i + 2 < len(sys.argv):
            maze_path = os.path.expanduser(sys.argv[sys.argv.index(arg) + 1])

    json_path = maze_path.replace('/csv/', '/maps/').replace('.csv', '.json')
    qtable_path = maze_path.replace('/csv/', '/maps/').replace('.csv', '_q_table.npy')

    rospy.init_node('q_learning_maze', anonymous=True)

    grid = load_grid(maze_path)
    start_cell, goal_cell, goal_gz, resolution, offset_x, offset_y = load_config(json_path)

    env = GridWorld(grid, start_cell, goal_cell)
    agent = QLearningAgent(env.n_rows, env.n_cols)

    if mode == '--train':
        action_pub = rospy.Publisher('/ql/action', String,         queue_size=10)
        state_pub = rospy.Publisher('/ql/state',  Int32MultiArray, queue_size=10)
        train_agent(env, agent, action_pub, state_pub)
        save_q_table(agent, qtable_path)
        env.print_grid()
        agent.print_policy(env)

    elif mode == '--test':
        load_q_table(agent, qtable_path)
        tester = GazeboTester(agent, env, goal_gz, resolution, offset_x, offset_y)
        tester.run()


if __name__ == '__main__':
    main()
